[workspace]

members = [
    "doublets-ffi",
    "doublets",

    # dev
    "dev-deps/mem-rs",
    "dev-deps/data-rs",
    "dev-deps/trees-rs",

    # internal
    "integration",
    
    # examples
    "examples/solver"
]
# in global rework
exclude = [
    "doublets-decorators",
]