[workspace]

members = [
    "doublets-ffi",
    "doublets",

    # web demo
    "web-demo",

    # dev
    "dev-deps/mem-rs",
    "dev-deps/data-rs",
    "dev-deps/trees-rs",

    # internal
    "integration"
]
# in global rework
exclude = [
    "doublets-decorators",
]